// This file was auto-generated by ML.NET Model Builder. 

using System;
using TaskBoardML.Model;

namespace TaskBoardML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Risk = @"dusuk",
                IslemTipi = @"duzeltme",
                Oncelik = @"musteri",
                TeknikUzman = @"rafet",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Sure with predicted Sure from sample data...\n\n");
            Console.WriteLine($"Risk: {sampleData.Risk}");
            Console.WriteLine($"IslemTipi: {sampleData.IslemTipi}");
            Console.WriteLine($"Oncelik: {sampleData.Oncelik}");
            Console.WriteLine($"TeknikUzman: {sampleData.TeknikUzman}");
            Console.WriteLine($"\n\nPredicted Sure: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
